title: Streamcode9 Blog
description: A space for sharing code experiments and musical riffs.
theme: minima

plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: /category/:name/
