# .github/workflows/pages.yml
name: Build & Deploy GitHub Pages (with WASM)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: 3.1.50

      - name: Build wasm
        run: |
          emcc -std=c89 -s STANDALONE_WASM=1 wasm/hello.c -o wasm/hello.wasm

      # If you use Jekyll, build here; otherwise just ship the repo contents.
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # ships your whole site, including wasm/hello.wasm

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
